brew "docker", link: false
brew "docker-compose", link: false
brew "exercism"
brew "git"
brew "go"
brew "gradle"
brew "node"
brew "jq"
brew "kafka"
brew "libevent"
brew "pyenv"
brew "rbenv"
brew "tmux"

